Factor analysis minor improvements
easystats/parameters pull request #877
Opened 2023-04-17 18:49 UTC by DominiqueMakowski

2023-04-17 18:51 UTC, DominiqueMakowski commented on R/principal_components.R
> -  # sanity check - we need at least two factors
This was making that whenever we ran `factor_analysis(mtcars, n=1)` it stubbornely returned 2 factors...

2023-04-17 19:13 UTC, strengejacke requested changes

2023-04-17 19:13 UTC, strengejacke commented on R/n_factors.R
> +    warning(paste0(
Use `insight::format_warning()` here

2023-04-17 19:13 UTC, strengejacke commented on R/cluster_analysis.R
> +  }
Use `insight::format_error()` here

2023-04-17 19:14 UTC, strengejacke commented
Any chance we can also have tests for this functionality? :-)

2023-04-18 10:14 UTC, strengejacke requested changes

2023-04-18 10:14 UTC, strengejacke commented on R/convert_efa_to_cfa.R
> +
Use `stats::na.omit()` here.

2023-04-18 10:14 UTC, strengejacke commented on R/n_factors.R
> +    n_Factors = as.numeric(na.omit(c(out$nfact, out$ncomp))),
Use `stats::na.omit()` here.

2023-04-18 10:14 UTC, strengejacke commented on R/n_factors.R
> +  out <- psych::fa.parallel(cor, n.obs = nobs, fa=fa, plot=FALSE, fm="ml")
Spaces around `=`.

2023-04-18 10:16 UTC, strengejacke requested changes

2023-04-18 10:16 UTC, strengejacke commented on R/convert_efa_to_cfa.R
> +                                  max_per_dimension = NULL,
`max_per_dimension` needs to be documented,

2023-04-18 10:18 UTC, strengejacke requested changes

2023-04-18 10:18 UTC, strengejacke commented on R/convert_efa_to_cfa.R
> +    if(!is.null(max_per_dimension) && max_per_dimension > 0) items <- as.character(na.omit(items[1:max_per_dimension]))
> Place a space before left parenthesis, except in a function call.

2023-04-18 10:18 UTC, strengejacke commented on R/cluster_analysis.R
> +  if(ncol(ori_data) <= 2) {
> Place a space before left parenthesis, except in a function call.

2023-04-18 10:18 UTC, strengejacke commented on R/n_factors.R
> +  if(!all(vapply(x, is.numeric, TRUE))) {
> Place a space before left parenthesis, except in a function call.

2023-04-18 10:18 UTC, strengejacke commented on R/n_factors.R
> +      paste0(names(x)[!vapply(x, is.numeric, TRUE)], collapse = ", "),
> toString(.) is more expressive than paste(., collapse = ", ")

2023-04-18 10:19 UTC, strengejacke commented
Furthermore:
- [ ] RD files need to be updated
- [ ] Tests added

2023-05-10 06:23 UTC, strengejacke commented
_bump_

2023-06-21 19:57 UTC, strengejacke commented
Can this be merged?

2023-07-14 07:45 UTC, strengejacke commented
@DominiqueMakowski can this be merged?

2023-09-11 20:18 UTC, DominiqueMakowski commented
Oh wow completely missed that. Yes I think it's good

2023-09-11 20:19 UTC, strengejacke commented
Let me see if checks pass, and then I'll merge.

2023-09-11 21:11 UTC, merged